#docker run -p 8080:8080 -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin
#quay.io/keycloak/keycloak:26.2.0 start-dev

services:
  # keycloak-db:
  #   image: mysql:8
  #   container_name: keycloak-db
  #   environment:
  #     MYSQL_DATABASE: keycloak
  #     MYSQL_USER: keycloak
  #     MYSQL_PASSWORD: password
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #   command: --default-authentication-plugin=mysql_native_password
  #   volumes:
  #     - keycloak-db-data:/var/lib/mysql
  #   networks:
  #     - keycloak-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    container_name: keycloak
    command:
      - start-dev
    environment:
      #KC_DB: mysql
      #KC_DB_URL: ${KC_DB_URL}
      #KC_DB_USERNAME: ${KC_DB_USERNAME}
      #KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8020:8080"
    networks:
      - keycloak-net
  nginx:
      image: nginx:alpine
      container_name: nginx-reverse-proxy
      ports:
        - "8022:80"
        - "8023:443"
      volumes:
        - ./nginx/conf:/etc/nginx/conf.d
        - ./nginx/certs:/etc/nginx/certs
      depends_on:
        - keycloak
      networks:
        - keycloak-net
# volumes:
#   keycloak-db-data:

networks:
  keycloak-net:
